INSERT INTO OFFERTE_LAVORO (AZIENDA, RETRIBUZIONE, ORE_GIORNALIERE, TIPO_CONTRATTO, RUOLO)
VALUES ("Intesys S.r.L.", 22000, 8, "Indeterminato", "Programmatore Java");

INSERT INTO SEDI (CITTA, VIA, N_CIVICO, CAP, ID_OFFERTA)
VALUES ("Verona", "Via Roveggia", 73, 37040, 1);

INSERT INTO COMPETENZE (DENOMINAZIONE, DESCRIZIONE)
VALUES ("Programmatore Java", "Programmatore back-end di Applicazioni in linguaggio Java");

INSERT INTO RICHIESTE(ID_OFFERTA, ID_COMPETENZA)
VALUES (1, 1);