
SELECT AZIENDA, RETRIBUZIONE, ORE_GIORNALIERE, RUOLO
FROM OFFERTE:LAVORO
LEFT JOIN RICHIESTE ON OFFERTE_LAVORO.ID_OFFERTA=RICHIESTE.ID_OFFERTA
LEFT JOIN COMPETENZE ON RICHIESTE.ID_COMPETENZA=COMPETENZE.ID_COMPETENZA
WHERE COMPETENZE.DENOMINAZIONE=[“inserisci denominazione competenza”];

SELECT AZIENDA, RETRIBUZIONE, ORE_GIORNALIERE, RUOLO
FROM OFFERTE:LAVORO
LEFT JOIN SEDI ON OFFERTE_LAVORO.ID_OFFERTA=SEDI.ID_OFFERTA
WHERE SEDI.CITTA=[“inserisci città dell’offerta”];