DROP DATABASE IF EXISTS AGENZIA;
CREATE DATABASE AGENZIA;
USE AGENZIA;

CREATE TABLE OFFERTE_LAVORO (
    ID_OFFERTA int NOT NULL AUTO_INCREMENT,
    AZIENDA char(35),
    RETRIBUZIONE int,
	ORE_GIORNALIERE int,
    TIPO_CONTRATTO char(35),
	RUOLO char(35),
    PRIMARY KEY (ID_OFFERTA)
);

CREATE TABLE SEDI (
    ID_SEDE int NOT NULL AUTO_INCREMENT,
	CITTA char(35),
    VIA char(40),
    N_CIVICO int,
    CAP int,
    ID_OFFERTA int,
    PRIMARY KEY (ID_SEDE),
	FOREIGN KEY (ID_OFFERTA) REFERENCES OFFERTE_LAVORO(ID_OFFERTA)
);

CREATE TABLE COMPETENZE (
    ID_COMPETENZA int NOT NULL AUTO_INCREMENT,
    DENOMINAZIONE char(35),
    DESCRIZIONE char(150),
   	PRIMARY KEY (ID_COMPETENZA)
);

CREATE TABLE RICHIESTE (
    ID_RICHIESTA int NOT NULL AUTO_INCREMENT,
    ID_OFFERTA int,
    ID_COMPETENZA int,
   	PRIMARY KEY (ID_RICHIESTA),
    FOREIGN KEY (ID_OFFERTA) REFERENCES OFFERTE_LAVORO(ID_OFFERTA),
    FOREIGN KEY (ID_COMPETENZA) REFERENCES COMPETENZE(ID_COMPETENZA)
);


